services:
  wallet-service:
    build: .
    container_name: wallet-service
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
    ports:
      - "8003:8003"
    mem_limit: 384m
    cpus: 0.7
    networks:
      - dhwaniastro-net

networks:
  dhwaniastro-net:
    external: true